### ISSUE TITLE
ansible-compat uses `--pre` unconditionally, even tho 2.9 does not support it

### ISSUE THREAD

**Issue by evgeni** [ansible/ansible-compat#162]
Ansible added `--pre` in 2.10 to `ansible-galaxy collection install`, but `ansible-compat` uses this also for Ansible 2.9, thus resulting in errors.

https://github.com/ansible/ansible-compat/blob/f6b38717e1203529924a6b04c4f19d35149da61b/src/ansible_compat/runtime.py#L219-L224

```
usage: ansible-galaxy [-h] [--version] [-v] TYPE ...
ansible-galaxy: error: unrecognized arguments: --pre
```

**Comment by ssbarnea** [comment]
We have very limited support for old ansible version, basically only a job testing with py38-ansible-2.9. If you make pull request to fix the issue that also adds a test for preventing regression I will be happy to add it.

Still, otherwise it is likely to be closes as won't fix, especially as soon we will probably remove 2.9 code too, as 2.14 will be out.
