### ISSUE TITLE
load_collections will fail if  ~/.ansible/collections cannot be created

### ISSUE THREAD

**Issue by MartinWallgren** [ansible/ansible-compat#279]
It is not guaranteed that `~/.ansible/collections` is the correct place to store collections and load_collections will fail if that directory cannot be created.

load_collections should probably use $ANSIBLE_HOME/collections as the directory to store collections in.

**Comment by sselberg** [comment]
And/or respect `ANSIBLE_LOCAL_TEMP`?

**Comment by hille721** [comment]
I run in this issue as well. In my case the `HOME` directory in my Gitlab CI is not writeable. Of course I could simply change that, but it was intended to test, that everything works without writing to ~. 
Since ansible 2.14 and the introduction of `ANSIBLE_HOME` ansible does not require it anymore.

As it is fixed here already, when I can expect that it will be reflected in ansible-lint as well?
